spring:
  data:
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./sandbox/datasource
    username: sa
    password:
    initialize: true
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always